### ISSUE TITLE
Cannot use SURF or SIFT on school computers

### ISSUE THREAD

**Issue by mgunyho** [AaltoVision/CV_course_py#2]
I tried to do exercise 4 on the school computers, but the `cv2.xfeatrues2d.SURF_create()` and `SIFT_create()` functions throw an error:

`cv2.error: OpenCV(3.4.3) /io/opencv_contrib/modules/xfeatures2d/src/surf.cpp:1016: error: (-213:The function/feature is not implemented) This algorithm is patented and is excluded in this configuration; Set OPENCV_ENABLE_NONFREE CMake option and rebuild the library in function 'create'`

My setup is pretty much following the instructions:
```
module load anaconda2
conda create -n CV_course python=2 numpy scipy matplotlib scikit-image scikit-learn jupyter
source activate CV_course
pip2 install opencv-python-contrib # opencv-python (without contrib) doesn't contain xfeatures2d
```
I used pip2 because pip3 is broken for some reason.

I tried also to do the exercises at home, but had the same problem with patents, and I'd rather not compile OpenCV myself.

**Comment by yjuha** [comment]
Our humble apologies for this hassle! So yes, everything should work if you have opencv compiled with the opencv-contrib and some flags turned on. But that was not of course the purpose that you were supposed to be able to do that...

As a solution, we have provided precomputed features and descriptors in the repo so these can be used instead of running xfeatures2d.sift/surf.detectAndCompute.
